server:
  port: 8080
  address: 127.0.0.1

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/wrist?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password:
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      #åˆå§‹åŒ–å¤§å°?
#      initialSize: 5
#      #æœ?å°å??
#      minIdle: 5
#      #æœ?å¤§å??
#      maxActive: 20
#      #æœ?å¤§ç­‰å¾…æ—¶é—´ï¼Œé…ç½®è·å–è¿æ¥ç­‰å¾…è¶…æ—¶ï¼Œæ—¶é—´å•ä½éƒ½æ˜¯æ¯«ç§’ms
#      maxWait: 60000
#      #é…ç½®é—´éš”å¤šä¹…æ‰è¿›è¡Œä¸€æ¬¡æ£€æµ‹ï¼Œæ£?æµ‹éœ€è¦å…³é—­çš„ç©ºé—²è¿æ¥
#      timeBetweenEvictionRunsMillis: 60000
#      #é…ç½®ä¸?ä¸ªè¿æ¥åœ¨æ± ä¸­æœ?å°ç”Ÿå­˜çš„æ—¶é—´
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      # é…ç½®ç›‘æ§ç»Ÿè®¡æ‹¦æˆªçš„filtersï¼Œå»æ‰åç›‘æ§ç•Œé¢sqlæ— æ³•ç»Ÿè®¡ï¼?
#      #'wall'ç”¨äºé˜²ç«å¢™ï¼ŒSpringBootä¸­æ²¡æœ‰log4jï¼Œæˆ‘æ”¹æˆäº†log4j2
#      filters: stat,wall,log4j2
#      #æœ?å¤§PSCacheè¿æ¥
#      maxPoolPreparedStatementPerConnectionSize: 20
#      useGlobalDataSourceStat: true
#      # é€šè¿‡connectPropertieså±æ?§æ¥æ‰“å¼€mergeSqlåŠŸèƒ½ï¼›æ…¢SQLè®°å½•
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#      # é…ç½®StatFilter
#      web-stat-filter:
#        #é»˜è®¤ä¸ºfalseï¼Œè®¾ç½®ä¸ºtrueå¯åŠ¨
#        enabled: true
#        url-pattern: "/*"
#        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
#      #é…ç½®StatViewServlet
#      stat-view-servlet:
#        url-pattern: "/druid/*"
#        #å…è®¸é‚£äº›ip
#        allow: 127.0.0.1
#        login-username: admin
#        login-password: 123456
#        #ç¦æ­¢é‚£äº›ip
#        deny: 192.168.1.102
#        #æ˜¯å¦å¯ä»¥é‡ç½®
#        reset-enable: true
#        #å¯ç”¨
#        enabled: true
#mybatis:
#  # modelçš„åŒ…
#  type-aliases-package: ssm.app.model
#  configuration:
#  ã€?ã€?# å¼?å¯é©¼å³°uNameè‡ªåŠ¨æ˜ å°„åˆ°u_name
#map-underscore-to-camel-case: true

# æ‰“å°sql
logging:
  level:
    ssm.app.mapper : debug